notifications:
  slack:
    rooms:
    - novegroup:SNV4w4RI7iU2gnStO5lhsPZI#github
  email: false

language: node_js
node_js:
  - "8"

before_install:
- sudo apt-get update
- npm install -g truffle@4.1.7 --silent
- npm install -g solhint@1.2.1 --silent
- npm install -g ganache-cli@6.0.3 --silent

all_branches: true

script:
- npm install --silent
- cd src/bc
- sed -i -e 's/metamask 20 word seed/drop where coast put actress bulk story pool margin cake slice age/g' truffle.js
- sed -i -e 's/<Infura key>/Rb9eRuYiPahM5vygdz1l/g' truffle.js
- cat truffle.js
- solhint ./contracts/*
- truffle compile
- ganache-cli -p 7545 -m velociraptor > artifacts.txt &
- truffle test
- pkill node
- cd ../..
- npm run lint
- npm run test

before_deploy:
- cd ./src/bc
- truffle migrate --network ropsten
- cd ../..
- npm run build
- ls
- cd build
- mv index.html 200.html
- ls
- cd ..
- ls

deploy:
  provider: surge
  file_glob: true
  skip_cleanup: true
  project: ./build/
  domain: velociraptor.surge.sh
  on:
    branch: master
