notifications:
  slack:
    rooms:
    - novegroup:SNV4w4RI7iU2gnStO5lhsPZI#github
  email: false

language: node_js
node_js:
  - "6"

before_install:
- sudo apt-get update
- npm install -g truffle@4.1.7
- npm install -g solhint
- npm install -g ganache-cli@6.0.3

all_branches: true

script:
- npm install 
- cd src/bc
- solhint ./contracts/*
- truffle compile
- ganache-cli -p 7545 -m velociraptor > artifacts.txt &
- truffle test
- pkill node
- cd ../..
- npm run lint
- npm run test

before_deploy:
- npm run build
- ls
- cd build
- mv index.html 200.html
- ls
- cd ..
- ls

deploy:
  provider: surge
  file_glob: true
  skip_cleanup: true
  project: ./build/
  domain: velociraptor.surge.sh
  on:
    branch: master
